name: vitameal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_hooks: ^0.21.3+1
  freezed_annotation: ^3.1.0
  hooks_riverpod: ^3.0.3
  json_annotation: ^4.9.0
  riverpod_annotation: ^3.0.3
  flutter_riverpod: ^3.0.3
  build_runner: ^2.7.1
  go_router: ^17.0.0
  intl: ^0.20.2
  image_picker: ^1.2.1
  supabase_flutter: ^2.12.0
  tap_debouncer: ^2.2.0
  table_calendar: ^3.2.0
  fl_chart: ^1.1.1
  shared_preferences: ^2.5.4
  flutter_image_compress: ^2.4.0
  connectivity_plus: ^7.0.0
  drift: ^2.25.0
  sqlite3_flutter_libs: ^0.5.41
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.2
  flutter_slidable: ^4.0.3
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  flutter_svg: ^2.2.3
  dropdown_button2: ^2.3.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.2
  riverpod_generator: ^3.0.3
  change_app_package_name: ^1.5.0
  drift_dev: ^2.25.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/


# dependencies:
#   flutter:
#     sdk: flutter
#   cupertino_icons: ^1.0.8
#   firebase_core: ^4.2.1
#   cloud_firestore: ^6.1.0
#   freezed_annotation: ^3.1.0
#   flutter_hooks: ^0.21.3+1
#   hooks_riverpod: ^3.0.3
#   json_annotation: ^4.9.0
#   riverpod_annotation: ^3.0.3
#   flutter_riverpod: ^3.0.3
#   build_runner: ^2.7.1
#   go_router: ^17.0.0
#   geolocator: ^14.0.2
#   dio: ^5.9.0
#   intl: ^0.20.2
#   kakao_flutter_sdk_user: ^1.10.0
#   firebase_auth: ^6.1.2
#   firebase_messaging: ^16.0.4
#   flutter_local_notifications: ^19.5.0
#   cloud_functions: ^6.0.4
#   shimmer: ^3.0.0
#   sqflite: ^2.4.2
#   path: ^1.9.1
#   image_picker: ^1.2.1
#   firebase_storage: ^13.0.4
#   lottie: ^3.3.2
#   flutter_svg: ^2.2.3
#   hugeicons: ^1.1.2
#   flutter_app_badger: ^1.5.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   freezed: ^3.2.3
#   flutter_lints: ^5.0.0
#   json_serializable: ^6.11.2
#   riverpod_generator: ^3.0.3
#   flutter_native_splash: ^2.4.7
#   flutter_launcher_icons: ^0.14.4